apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-whb
data:
  krakend.json: |
    {
    "$schema": "https://www.krakend.io/schema/v3.json",
    "version": 3,
    "name": "KrakenD Enterprise API Gateway",
    "port": 8080,
    "host": ["http://api-fitzdares.rs.fsbtech.com:8080"],
    "timeout": "3000ms",
    "cache_ttl": "300s",
    "endpoints": [
      {
        "@comment": "Feature: Mocked response",
        "endpoint": "/mocked-response",
        "method": "GET",
        "output_encoding": "json",
        "backend": [{"host": ["http://unexistent_backend"], "url_pattern": "/"}],
        "extra_config": {
          "proxy": {
            "static": {
              "data": {
                "an_integer": 123,
                "an_array": [
                  "arr1",
                  "arr2"
                ],
                "an_object": {
                  "obj": "obj1"
                }
              },
              "strategy": "always"
            }
          }
        }
      }
    ],
    "sequential_start": true,
    "extra_config": {
      "security/cors": {
        "allow_origins": ["*"],
        "allow_methods": ["POST", "GET"],
        "allow_headers": ["Origin", "Authorization", "Content-Type"],
        "expose_headers": ["Content-Length"],
        "max_age": "12h"
      },
      "auth/revoker": {
        "N": 10000000,
        "P": 0.0000001,
        "hash_name": "optimal",
        "TTL": 1500,
        "port": 1234,
        "token_keys": ["jti"]
      }
    }
    }
  